name: learning_rewards_from_language
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - brotlipy=0.7.0=py38h64e0658_1000
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cffi=1.14.0=py38hc512035_1
  - chardet=3.0.4=py38h32f6830_1006
  - cryptography=2.9.2=py38hb761dab_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.14=h517e14e_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.63.1=h70d4741_1
  - icu=58.2=h0a44026_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py38_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=2.1.4=py_0
  - jupyterlab_server=1.1.5=py_0
  - kiwisolver=1.2.0=py38h04f5b5a_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.1.0=hcb84e12_1
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h0a44026_0
  - markupsafe=1.1.1=py38h1de35cc_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h9aa3819_0
  - mistune=0.8.4=py38h1de35cc_1000
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.1=py38h959d312_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_1
  - ninja=1.9.0=py38h04f5b5a_0
  - nltk=3.4.5=py38_0
  - notebook=6.0.3=py38_0
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h3304bdc_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h1de35cc_0
  - pandas=1.0.3=py38h6c726b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.1.2=py38h4655f20_0
  - pip=20.0.2=py38_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - ptyprocess=0.6.0=py38_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.16.0=py38h1de35cc_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.3=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.5.0=py3.8_0
  - pytz=2020.1=py_0
  - pyzmq=18.1.1=py38h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.4=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.22.1=py38h27c97d8_0
  - scipy=1.4.1=py38h44e99c9_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py38_0
  - setuptools=47.1.1=py38_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h5c1f38d_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - torchvision=0.6.0=py38_cpu
  - tornado=6.0.4=py38h1de35cc_1
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.1=h0a44026_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h1990bb4_3
prefix: /opt/anaconda3/envs/learning_rewards_from_language

